name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      - run: node --version
      - run: npm --version
